version: '3'

services: 
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=postgres

  memcached:
    image: memcached

  redis1:
    image: redis
  redis2:
    image: redis

  application:
    image: "socialsirius/didcomm:${VERSION-dev}"
    command: bash -c "sleep 90s; /app/run_tests.sh"
    environment:
      - TEAMCITY_VERSION
      - MEMCACHED=memcached
      - REDIS=redis://redis1,redis://redis2
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - WEBROOT=http://didcomm.server.com
      - SEED=000000000000000000000000000RELAY
      - LOGLEVEL=DEBUG
      - FCM_API_KEY=fake-key
      - FCM_SENDER_ID=fake-id
    depends_on:
      - db
      - memcached
      - redis1
      - redis2
