version: '3'

services: 
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=postgres

  memcached:
    image: memcached

  redis1:
    image: redis
  redis2:
    image: redis

  nginx:
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']  # Run nginx in debug mode
    volumes:
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  application:
    build: 
      context: .
    image: "socialsirius/didcomm:${VERSION-dev}"
    environment:
      - TEAMCITY_VERSION
      - MEMCACHED=memcached
      - REDIS=redis1,redis2
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - WEBROOT=http://didcomm.server.com
      - SEED=000000000000000000000000000RELAY
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
      - redis1
      - redis2
      - nginx
